### ISSUE TITLE
FeatureRequest: Option to disable make multi job

### ISSUE THREAD

**Issue by has213** [bmd-studio/stm32-for-vscode#138]
Hi,
your Plugin is very helpful.

The problem is if make uses multiple jobs (-j16), the terminal output is scrambled and the problem matcher can't work correctly. So useful warnings from the Compiler  can get lost easily.

I know that for faster compilation, multi jobs are useful. This is why I suggest an Option or perhaps a build (singeljob) comment.
Maybe You can make a setting/option to configure the job number yourself.

**Comment by jortbmd** [comment]
Hi! Thanks for opening up an issue for this. This issue is only present in newer versions of make. There was a similar issue before and a fix has been implemented. There is a special makeFlags option in the STM32-for-VSCode.config.yaml. Where you can add the -O flag e.g.: 
```
makeFlags:
 - -O
 ```
 For more info on the earlier issue: https://github.com/bmd-studio/stm32-for-vscode/issues/119
 
 As this should fix the issue I will close this issue for now. If you still continue to have problems after this feel free to reopen this issue or create a new one.
