### ISSUE TITLE
Version 3.2.7 not available in version list

### ISSUE THREAD

**Issue by DeflateAwning** [bmd-studio/stm32-for-vscode#208]
In the VS Code "Install specific version" list, there's no 3.2.7 release version. 

![image](https://github.com/user-attachments/assets/8510bb6c-9cee-4010-b5a1-298e4942363c)

**Comment by jortbmd** [comment]
Thanks for opening up an issue for this. The 3.2.7 was in beta for long and did not release it due to some issues with building projects which have files from the parent scope (still present). Due to other issues and feature request I bumped the version and released 3.2.8. Closing this issue for now as I don't mind skipping a version.

**Comment by DeflateAwning** [comment]
Makes sense, thanks a lot!
