### ISSUE TITLE
This extension requires: "st-flash" to be available in PATH, please install make for your specific environment

### ISSUE THREAD

**Issue by wangxiufeng1104** [bmd-studio/stm32-for-vscode#4]
My settings：
"stm32-for-vscode.makePath": "C:\\Program Files (x86)\\GnuWin32\\bin"
"stm32-for-vscode.st-flashPath": "C:\\Program Files (x86)\\STMicroelectronics\\STM32 ST-LINK Utility\\ST-LINK Utility\\",
How can I solve it?

**Comment by jortbmd** [comment]
Hi,

Did a quick look. It appears that there is still a bug in getting the path for the ST-flash utility. This will be fixed in a next release, which is coming somewhere this week. For now the work around would be to add the utility to your PATH variable. A tutorial of this can be found here. https://docs.alfresco.com/4.2/tasks/fot-addpath.html.
